### ISSUE TITLE
Inoperable on VRC 1114 (ML 0.4.1)

### ISSUE THREAD

**Issue by Anonymous-BCFED** [ddakebono/BTKSASelfPortrait#3]
Camera window has stopped working, starting on VRC 1113/ML 0.4.1, running v1.2.0 of BTKSASelfPortrait.  No errors in console, only message is the startup.

**Comment by ddakebono** [comment]
Yea, been hearing that. My potato brain forgot a line of code and no settings are being loaded at startup. I'll have it fixed tonight, but it'll have to get through the validation still.

**Comment by ddakebono** [comment]
Fixed in release 1.2.1
