### ISSUE TITLE
Needs SPSI VR Support

### ISSUE THREAD

**Issue by DippyFoxDerg** [ddakebono/BTKSASelfPortrait#6]
ChilloutVR Upgraded to Unity 2021.3.23f1. The mod in its current state, the portrait only appears in the left eye. so to fix this the mod needs to support Single Pass Stereo Instanced Rendering mode for VR.

**Comment by DippyFoxDerg** [comment]
it appears to be fixed now, thank you so much~

**Comment by ddakebono** [comment]
Yep, just needed a rebuild of the assets. Forgot to close this out when I published the release.
